from src.db import init_db, save_match

init_db()

results = [
    {
        "decision": "matched",
        "receipt_id": "r1",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r1 matches the exact transaction amount of $14.50, the exact date (2026-06-01), and the vendor name 'Joe's Diner' corresponds directly to the bank description 'SQ *JOES DINER'.",
        "transaction_date": "2026-06-01",
        "transaction_desc": "SQ *JOES DINER",
        "transaction_amount": -14.5,
    },
    {
        "decision": "matched",
        "receipt_id": "r2",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r2 matches the transaction amount of $6.75, the transaction date of 2026-06-02, and the vendor Starbucks with high confidence.",
        "transaction_date": "2026-06-02",
        "transaction_desc": "STARBUCKS #4521",
        "transaction_amount": -6.75,
    },
    {
        "decision": "matched",
        "receipt_id": "r3",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The bank transaction amount ($42.99) and date (2026-06-03) match receipt r3 exactly, and the vendor abbreviation clearly corresponds to Amazon.com.",
        "transaction_date": "2026-06-03",
        "transaction_desc": "AMZN MKTP US*2K3L9",
        "transaction_amount": -42.99,
    },
    {
        "decision": "matched",
        "receipt_id": "r4",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The candidate receipt r4 has an exact amount match (18.30), an exact date match, and a clear vendor name match.",
        "transaction_date": "2026-06-04",
        "transaction_desc": "UBER *TRIP HELP.UBER.COM",
        "transaction_amount": -18.3,
    },
    {
        "decision": "matched",
        "receipt_id": "r5",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The transaction amount ($5.25) exactly matches receipt r5 ('The Coffee Shop'), the date matches perfectly.",
        "transaction_date": "2026-06-05",
        "transaction_desc": "TST* COFFEE SHOP",
        "transaction_amount": -5.25,
    },
    {
        "decision": "matched",
        "receipt_id": "r6",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r6 matches the transaction date, exact amount ($7.10), and vendor name (Starbucks).",
        "transaction_date": "2026-06-06",
        "transaction_desc": "STARBUCKS #7793",
        "transaction_amount": -7.1,
    },
    {
        "decision": "matched",
        "receipt_id": "r7",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r7 has the exact matching amount ($15.49), a matching vendor name (Netflix), and a date within 1 day.",
        "transaction_date": "2026-06-08",
        "transaction_desc": "NETFLIX.COM",
        "transaction_amount": -15.49,
    },
    {
        "decision": "no_match",
        "receipt_id": None,
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "None of the candidate receipts match the transaction amount of $22.00 or the vendor 'SQ *JOES DINER'.",
        "transaction_date": "2026-06-09",
        "transaction_desc": "SQ *JOES DINER",
        "transaction_amount": -22.0,
    },
    {
        "decision": "no_match",
        "receipt_id": None,
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Amount and vendor plausible but flagged as no_match by model on this run (edge case near date boundary).",
        "transaction_date": "2026-06-10",
        "transaction_desc": "WM SUPERCENTER #3312",
        "transaction_amount": -63.42,
    },
    {
        "decision": "matched",
        "receipt_id": "r9",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r9 (Lyft) has the exact matching amount of $12.85 and a date within the tolerance window.",
        "transaction_date": "2026-06-11",
        "transaction_desc": "LYFT *RIDE THU 8PM",
        "transaction_amount": -12.85,
    },
    {
        "decision": "matched",
        "receipt_id": "r10",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The transaction amount ($29.99) matches receipt r10 exactly; vendor corresponds to Amazon.com.",
        "transaction_date": "2026-06-12",
        "transaction_desc": "AMZN MKTP US*7H2P1",
        "transaction_amount": -29.99,
    },
    {
        "decision": "matched",
        "receipt_id": "r11",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r11 matches the transaction amount of $9.40 and the vendor name 'Bagel Corner'.",
        "transaction_date": "2026-06-14",
        "transaction_desc": "TST* BAGEL CORNER",
        "transaction_amount": -9.4,
    },
    {
        "decision": "matched",
        "receipt_id": "r12",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r12 from 'Office Depot' matches the transaction amount of $54.10 exactly.",
        "transaction_date": "2026-06-15",
        "transaction_desc": "OFFICE DPT #221",
        "transaction_amount": -54.1,
    },
    {
        "decision": "matched",
        "receipt_id": "r13",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The transaction amount ($19.50) and date match receipt r13 (Thai Garden Restaurant) exactly.",
        "transaction_date": "2026-06-16",
        "transaction_desc": "SQ *THAI GRDN",
        "transaction_amount": -19.5,
    },
    {
        "decision": "matched",
        "receipt_id": "r15",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r15 matches the exact transaction amount of $412.0; vendor 'Delta Air Lines' corresponds to 'DELTA AIR'.",
        "transaction_date": "2026-06-18",
        "transaction_desc": "DELTA AIR 0062314",
        "transaction_amount": -412.0,
    },
    {
        "decision": "no_match",
        "receipt_id": None,
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "None of the candidate receipts match the transaction amount of $16.75 (refund) or the vendor.",
        "transaction_date": "2026-06-20",
        "transaction_desc": "SQ *JOES DINER",
        "transaction_amount": 16.75,
    },
    {
        "decision": "matched",
        "receipt_id": "r16",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The transaction description 'ADBE *ADOBE CREATIVE' matches the vendor 'Adobe Creative Cloud' on receipt r16.",
        "transaction_date": "2026-06-21",
        "transaction_desc": "ADBE *ADOBE CREATIVE",
        "transaction_amount": -54.99,
    },
    {
        "decision": "matched",
        "receipt_id": "r17",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The transaction amount ($7.00) and date match receipt r17 (GitHub) within the 3-day date tolerance.",
        "transaction_date": "2026-06-23",
        "transaction_desc": "GITHUB.COM",
        "transaction_amount": -7.0,
    },
    {
        "decision": "matched",
        "receipt_id": "r18",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The amount ($13.20) matches exactly; vendor 'Chipotle Mexican Grill' corresponds directly to 'CHIPOTLE 0334'.",
        "transaction_date": "2026-06-25",
        "transaction_desc": "CHIPOTLE 0334",
        "transaction_amount": -13.2,
    },
    {
        "decision": "no_match",
        "receipt_id": None,
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "None of the candidate receipts match the transaction amount of $48.00 or the vendor 'SHELL OIL' (fuel).",
        "transaction_date": "2026-06-27",
        "transaction_desc": "SHELL OIL 57443210",
        "transaction_amount": -48.0,
    },
    {
        "decision": "no_match",
        "receipt_id": None,
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "None of the candidate receipts match the transaction amount ($5.75) or vendor within a reasonable date range.",
        "transaction_date": "2026-06-29",
        "transaction_desc": "TST* COFFEE SHOP",
        "transaction_amount": -5.75,
    },
    {
        "decision": "no_match",
        "receipt_id": None,
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "None of the candidate receipts match the amount ($11.85) or vendor (Panera Bread) of the bank transaction.",
        "transaction_date": "2026-07-01",
        "transaction_desc": "PANERA BREAD #602",
        "transaction_amount": -11.85,
    },
    {
        "decision": "matched",
        "receipt_id": "r20",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "Receipt r20 matches the transaction amount ($19.99), is within 1 day of the transaction date.",
        "transaction_date": "2026-07-03",
        "transaction_desc": "AMZN MKTP US*9Q4R2",
        "transaction_amount": -19.99,
    },
    {
        "decision": "matched",
        "receipt_id": "r19",
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "The transaction amount ($24.60) exactly matches candidate r19's total amount; vendor 'Uber' matches.",
        "transaction_date": "2026-07-05",
        "transaction_desc": "UBER *TRIP HELP.UBER.COM",
        "transaction_amount": -24.6,
    },
    {
        "decision": "no_match",
        "receipt_id": None,
        "confidence": "high",
        "clarifying_question": None,
        "reasoning": "None of the candidate receipts match the transaction amount ($14.99) or vendor (ZOOM.US).",
        "transaction_date": "2026-07-08",
        "transaction_desc": "ZOOM.US",
        "transaction_amount": -14.99,
    },
]

for r in results:
    save_match(r)

print(f"Seeded {len(results)} transactions into the database.")
